# yamllint disable
# #? sops --encrypt --in-place "cluster/apps/networking/cloudflare-ddns/secret.sops.yaml"
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
# CLOUDFLARE_EMAIL: The email used to log into https://dash.cloudflare.com
# CLOUDFLARE_APIKEY: Top right corner, "My profile" > "Global API Key"
# CLOUDFLARE_ZONEID: Can be found in the "Overview" tab of your domain
# CLOUDFLARE_RECORD_NAME: The name of your A record
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:V3hoETq3Uo/XJPx4LJMD3DsQ/hcp,iv:2mXzHXQ/Z4GixvBdS1nXNi+Huge7zal4mUOUhouw6sY=,tag:IOrHesnZataREo6UkwVeJA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:X+dCwW6Dy0KFGnhvWgbKdmHWWM7XZINgXNoEY8QQ987Y7iwBYQ==,iv:A3skeLDWepo1voXHXcOn5ioPwIzt6ZOnLvohwK2ri90=,tag:bXSdN7/GtoczgeDmKtinBA==,type:str]
    CLOUDFLARE_ZONEID: ENC[AES256_GCM,data:QLZYFpG+5xz+CLhLQuV9+mYzWZDUqTN+Amksj9TBPS0=,iv:iwaHhlZYRBGzLeIQ8o8VrU5GTzlDXdXW4alcCazrldU=,tag:sKCAn1RYD6EutnTgVGwwgw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:A/yGwzsk6b0XC1WLgq653p6zNXKW,iv:HzYV4aqUPuQTJqUDRcixl4jtS4KRqsnaw7aAlV6JPxI=,tag:A3/Ez+EQ4argb3CzYl7cHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l2ynvs6f5sug5hf5yzd3dedd4yusth2rwxg77xxllg8kgcdd2f8sw965ed
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpamlrVkRoMFhhZlJjb2R6
            UHI3VFFHUUZDVUZqSDRCbnNBcVJ6eVBjNlJJCnRCbGdZZXJWb0gxNEM1OEFGeTA1
            ckpDNFkwZjR1V1hqYVdabGwzSEZnQ0kKLS0tIGh1REhXbDdxS2JSd1Z4TXU0Ylhj
            TkQxbW4wYVpUdnoveVN2MWdUTWpDTzAKgYOwdzW3QoIpB/CfiInFwL8yyLk1A05e
            cGl/MTEOLavCykmDViRs/cZozEd77JlJf3+M9Ih1/C0f5aJYHjgJdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-13T18:46:03Z"
    mac: ENC[AES256_GCM,data:AlCV/d390WEDSpaLZOQ1uDe6b7Pba4evd0Y3GXsV8KGB5fkZgg5kRyVn/fcIlIZWx6olMvymKY9DUYHRQvux9VEhMp+pWPeMBxt2Dg5/XFHF2xrd0CkZWYzEEezwj53xFTgTOv4Y4jucEyVR4Qh5s/AZaF7L83humNdOoRYVO4o=,iv:a2T+kHF+dDahK2Z74YAUeHq1VgI74HPJoV1qVR0VCeg=,tag:F31EzKr3SUw4lLD4IM9ojA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
