---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: media
  labels:
    kasten-io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hdd-nfs-storage
  resources:
    requests:
      storage: 30Gi
