# yamllint disable
# #? sops --encrypt --in-place "cluster/base/cluster-secrets.sops.yaml"
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
    annotations:
        # https://github.com/emberstack/kubernetes-reflector/releases/latest/download/reflector.yaml
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        #,downloads
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: default,networking,media,storage,vpn-gateway,monitoring
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:z68oM7qoumRc21selHB8Vg==,iv:IMTwoUQhaN1HQuQkZ1y8nEkGBs1O92i4JkEgM+QK6x8=,tag:d1Dpu1l9OaR8vWvkR4ei2w==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:55Kl1Fo9yN4gp7JqHzHNEg7t1mf8,iv:cZG8Xm1YbdCrpVarSteLAGY801OPbzlQs+eliW1rnAA=,tag:pr+yQC9D4rRbSGiI/3wwCg==,type:str]
    SECRET_CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:TXzyfPOkUg71s4BvRP8eHnyAA6W7ImAzpfikJZxAgr53NPpWSg==,iv:jK6x2QHNvSBUkh4nwyprSdO1k/shJIX1/dVjdyEmGvs=,tag:PSXsgL0OYH0HFdMOfTTOpg==,type:str]
    SECRET_CLOUDFLARE_ZONEID: ENC[AES256_GCM,data:hfoqjPnaZLnDsRXMopCosJBHDxgjEIy280L2thcQYtM=,iv:tWvnI1rzvHA4koqJdRuaTzTGBbYy9nZip7cMLC6IzVQ=,tag:tONMOt5+gRLsMngI/mZ9KA==,type:str]
    SECRET_CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:4XbgsItDjOjhXMwdt58fdgk0ISF9,iv:gvtDLHRTQ9/Udcp7Jhp/NNmC9+8JbJ3qFHbEIVaV640=,tag:dlcqEB2V7ltwPsyYV20R2Q==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:00047HD/01dBe8M=,iv:uXTDEP4EK8tXWGxcc9pggBMJ6hiW9B5pF+RKa9ryYjM=,tag:YekyLDIOljufqwcDa+tI/g==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:FxZ4vbjInCD/AKaYw/lrw2LTJ/g08Scf,iv:bsg0P1Gl+g2jfEfHr8aydSQEAL2GCGK8auJv5irsvDM=,tag:Z4tpGd7jeX7ps/HoyFB/kA==,type:str]
    SECRET_PROVIDERS_GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:k5PY36nuKHWSzXFvf2z4mhYCaJFLSk8Rjr97btO1a94rYjOn9roMlTJ7tKTF/1q/gizmPT2Bzr8JZYneONcc+vUY3Z4Ga0rG,iv:gIts/BDkC9xQgSXCjQXhiCkYKT21bnaVYIvr4xh+fVk=,tag:ElTtsim+DjElTN4ZfAiW8A==,type:str]
    SECRET_PROVIDERS_GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:tHO9xvuHJ2kWDx0H3l1eLg4ZGO2/zKMt,iv:I3vl7+QyVcDUG8gSxef0pug6eleRqPenPdJKTtwWxYI=,tag:FjVqIPoGUJe/QRctUv6cxQ==,type:str]
    SECRET_OAUTH_SECRET: ENC[AES256_GCM,data:E2geG6OIbYYhbbU7essWHQz9F248C0Ss9GNRNF/1Sco=,iv:+Zx0EZt1mJKtPWW4DlMbQ282mjtxS0eHjOnBPvgUhIM=,tag:N56S8MRfET2GVl3gp9n3TA==,type:str]
    SECRET_WHITELIST: ENC[AES256_GCM,data:sL6GbBnLrw1KA2C4NvvdxpWUWPGP,iv:Ml5q/JowD1Vt3nOgRoKvEeKZiZ/R7vFk7OZ2al/6Tyc=,tag:KV+W+G+5nk/RMyU9SgLH/w==,type:str]
    SECRET_VPN_COUNTRY: ENC[AES256_GCM,data:rcg=,iv:u+a+NFALXYRoOeqdMoY2SQOubvu3X5QxR+7NvKHE36E=,tag:dOK91stXm9munrkcwFnEJg==,type:str]
    #ENC[AES256_GCM,data:kn7iMt/yMhqRzVZfh8Uz2WoEs6E2K4LUajrtWENYloMp+K5YPWMEaBth+JwNmS8ioojBRiwbgTIrdHiB9fzeAekp0x1wxj5/QZFEhnv15NEx2nz7+Zg2M7SKbia3ssOyKLk6O4s01vyiHr/MHgUowUM8GMtEWuRraitHXqQ00H/BsCOMV2NSie9zvKK4ZvrJ7Y9hFVGy,iv:fip6GUWQrePsNfQeYkdwRXeSbCsa9JZ0sO40Vu6BNmc=,tag:ZbVJQuCcB0frdzyVvDDg+g==,type:comment]
    #ENC[AES256_GCM,data:JGmgjRNCiJCj5uwrhqlJ8AEu6O/CzdMfveH1PomyP04Sv+JkW5qodMyfs96psPZhbyNK6ugSBnfMvm37lv6S2j0BWg==,iv:zU/msMTRTCwqnAmj2qpwti05Mfy14H3ki2kvWXUR1O8=,tag:BNdJvAGvPuyRudHxDj7/qg==,type:comment]
    SECRET_PLEX_CLAIM_TOKEN: ENC[AES256_GCM,data:Cjiw/e1V6NjrE73Byre373xYjsOWegb28Xg=,iv:rjqUqOCHaGYz675ba02Td/YQcdfdn7yDsO97jNZ9Io0=,tag:FkFj7zWVO3n3BzO/W5uQEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l2ynvs6f5sug5hf5yzd3dedd4yusth2rwxg77xxllg8kgcdd2f8sw965ed
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTm1kNDFUZWdxREFHdklt
            cmhuQlRJd3BmNmhlYjB1QTcyaDkxb0FLMHpvClFxaDg2VUVJVlNUYXRaZmJxZDdU
            R1UvREIweTJNaDl6Z0prZUFaZ1hWd28KLS0tIDJYS1BxRDlidVVhbDJWdW1RVWpQ
            Yk1DcHZ2Y2hFb1hiK0p6cmtsY090cjgK/xFng2OpSAFuG2goB7K6xl7l7Ku+RIy+
            apAabsfWWgEr4MBvdLiJJQFmoSPqoLy6exHGdU3K4m0GpCWECzVLBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-10T22:05:37Z"
    mac: ENC[AES256_GCM,data:gtVaDdt6yU0FcDrYTzDBjDz0Iz8OO+mzKqp9OgABXbLCmzFDgNL/GoJFGnA3Jv9+g9yh/wo8EMtZozB8z/iZuTFDfvII3BnHlCWP+/BAimNYsFYzOEkc8S8nuq1YKWWSnWBqww2AP32SMdQXQNgHx3chHTg3yDlRlW/4nZQrBpw=,iv:25A6Vdg/wgsR/LwqFHgw1aWA7FldQ69MHXrdxf/cU+I=,tag:ySPLIfQDrgDCIQNo30t6RQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
