# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:z68oM7qoumRc21selHB8Vg==,iv:IMTwoUQhaN1HQuQkZ1y8nEkGBs1O92i4JkEgM+QK6x8=,tag:d1Dpu1l9OaR8vWvkR4ei2w==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:55Kl1Fo9yN4gp7JqHzHNEg7t1mf8,iv:cZG8Xm1YbdCrpVarSteLAGY801OPbzlQs+eliW1rnAA=,tag:pr+yQC9D4rRbSGiI/3wwCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l2ynvs6f5sug5hf5yzd3dedd4yusth2rwxg77xxllg8kgcdd2f8sw965ed
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTm1kNDFUZWdxREFHdklt
            cmhuQlRJd3BmNmhlYjB1QTcyaDkxb0FLMHpvClFxaDg2VUVJVlNUYXRaZmJxZDdU
            R1UvREIweTJNaDl6Z0prZUFaZ1hWd28KLS0tIDJYS1BxRDlidVVhbDJWdW1RVWpQ
            Yk1DcHZ2Y2hFb1hiK0p6cmtsY090cjgK/xFng2OpSAFuG2goB7K6xl7l7Ku+RIy+
            apAabsfWWgEr4MBvdLiJJQFmoSPqoLy6exHGdU3K4m0GpCWECzVLBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-13T18:21:46Z"
    mac: ENC[AES256_GCM,data:kzDrTmAsD2+s34XwP38YCzg5OjivqpYK705UJ5VLfzbKaufT00eHj9GGtCQuw2V9ExMmxDrnzC6FG1mPffSrHjKP7eOkujxL3nHgKvPg0hFzWtLw+042Zf4IR+tMV0lcK7UYSz0RE1/T2jCaRpyfHbu8iM4NKcWc5/7bWKFeQLI=,iv:gujmpBKV9ALKixFCVox2af6Bq3lf4zSMTllFzscV1nQ=,tag:ECfGx1J4MqeM64dUAkMvSw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
