# yamllint disable
# #? sops --encrypt --in-place "cluster/base/cluster-secrets.sops.yaml"
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
    annotations:
        # https://github.com/emberstack/kubernetes-reflector/releases/latest/download/reflector.yaml
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: default,networking,media,storage
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:z68oM7qoumRc21selHB8Vg==,iv:IMTwoUQhaN1HQuQkZ1y8nEkGBs1O92i4JkEgM+QK6x8=,tag:d1Dpu1l9OaR8vWvkR4ei2w==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:55Kl1Fo9yN4gp7JqHzHNEg7t1mf8,iv:cZG8Xm1YbdCrpVarSteLAGY801OPbzlQs+eliW1rnAA=,tag:pr+yQC9D4rRbSGiI/3wwCg==,type:str]
    SECRET_CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:TXzyfPOkUg71s4BvRP8eHnyAA6W7ImAzpfikJZxAgr53NPpWSg==,iv:jK6x2QHNvSBUkh4nwyprSdO1k/shJIX1/dVjdyEmGvs=,tag:PSXsgL0OYH0HFdMOfTTOpg==,type:str]
    SECRET_CLOUDFLARE_ZONEID: ENC[AES256_GCM,data:hfoqjPnaZLnDsRXMopCosJBHDxgjEIy280L2thcQYtM=,iv:tWvnI1rzvHA4koqJdRuaTzTGBbYy9nZip7cMLC6IzVQ=,tag:tONMOt5+gRLsMngI/mZ9KA==,type:str]
    SECRET_CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:4XbgsItDjOjhXMwdt58fdgk0ISF9,iv:gvtDLHRTQ9/Udcp7Jhp/NNmC9+8JbJ3qFHbEIVaV640=,tag:dlcqEB2V7ltwPsyYV20R2Q==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:00047HD/01dBe8M=,iv:uXTDEP4EK8tXWGxcc9pggBMJ6hiW9B5pF+RKa9ryYjM=,tag:YekyLDIOljufqwcDa+tI/g==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:FxZ4vbjInCD/AKaYw/lrw2LTJ/g08Scf,iv:bsg0P1Gl+g2jfEfHr8aydSQEAL2GCGK8auJv5irsvDM=,tag:Z4tpGd7jeX7ps/HoyFB/kA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l2ynvs6f5sug5hf5yzd3dedd4yusth2rwxg77xxllg8kgcdd2f8sw965ed
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTm1kNDFUZWdxREFHdklt
            cmhuQlRJd3BmNmhlYjB1QTcyaDkxb0FLMHpvClFxaDg2VUVJVlNUYXRaZmJxZDdU
            R1UvREIweTJNaDl6Z0prZUFaZ1hWd28KLS0tIDJYS1BxRDlidVVhbDJWdW1RVWpQ
            Yk1DcHZ2Y2hFb1hiK0p6cmtsY090cjgK/xFng2OpSAFuG2goB7K6xl7l7Ku+RIy+
            apAabsfWWgEr4MBvdLiJJQFmoSPqoLy6exHGdU3K4m0GpCWECzVLBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-21T18:00:51Z"
    mac: ENC[AES256_GCM,data:+04hjg5BKU8a7hAEwD+mE9eCO5YMgRBVzjNPiJpG6mEyXAbG2iMQrwYJ6tmG86kXU/ZmZRdr8r2d3Esg4Wf+Sgyv5i5FZDn900edHgX+SqZGTyGub5e35ABN1KwJ8NGMgnVzPa/MRK7CeBaJh+ZCO9T74gIYpb3gZJXw6ELWGZQ=,iv:vTc8BWgF9OMIr1cPQ3AdeGxkXkNT/uJTpPPV274Nxpc=,tag:2pSBWpdFRegrQJeyhUIJ4A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
