---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cloudflare-ddns
  namespace: networking
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  jobTemplate:
    metadata:
      annotations:
        botkube.io/disable: 'true'
    spec:
      backoffLimit: 3
      template:
        metadata:
          annotations:
            botkube.io/disable: 'true'
        spec:
          containers:
            - command:
                - /bin/sh
                - /app/cloudflare-ddns.sh
              envFrom:
                - secretRef:
                    name: cloudflare-ddns
              image: ghcr.io/k8s-at-home/kubectl:v1.23.3
              name: cloudflare-ddns
              volumeMounts:
                - mountPath: /app/cloudflare-ddns.sh
                  name: cloudflare-ddns
                  readOnly: true
                  subPath: cloudflare-ddns.sh
          restartPolicy: Never
          volumes:
            - name: cloudflare-ddns
              projected:
                defaultMode: 775
                sources:
                  - configMap:
                      items:
                        - key: cloudflare-ddns.sh
                          path: cloudflare-ddns.sh
                      name: cloudflare-ddns
      ttlSecondsAfterFinished: 300
  schedule: '*/5 * * * *'
  successfulJobsHistoryLimit: 3
---
# apiVersion: batch/v1
# kind: CronJob
# metadata:
#   name: cloudflare-ddns
#   namespace: networking
# spec:
#   concurrencyPolicy: Forbid
#   failedJobsHistoryLimit: 5
#   jobTemplate:
#     metadata:
#       annotations:
#         botkube.io/disable: 'true'
#     spec:
#       backoffLimit: 3
#       template:
#         metadata:
#           annotations:
#             botkube.io/disable: 'true'
#         spec:
#           containers:
#             - command:
#                 - /bin/sh
#                 - /app/cloudflare-ddns.sh
#               envFrom:
#                 - secretRef:
#                     name: cloudflare-ddns
#               image: ghcr.io/k8s-at-home/kubectl:v1.23.3
#               name: cloudflare-ddns
#               volumeMounts:
#                 - mountPath: /app/cloudflare-ddns.sh
#                   name: cloudflare-ddns
#                   readOnly: true
#                   subPath: cloudflare-ddns.sh
#           restartPolicy: Never
#           volumes:
#             - name: cloudflare-ddns
#               projected:
#                 defaultMode: 775
#                 sources:
#                   - configMap:
#                       items:
#                         - key: cloudflare-ddns.sh
#                           path: cloudflare-ddns.sh
#                       name: cloudflare-ddns
#       ttlSecondsAfterFinished: 300
#   schedule: '*/5 * * * *'
#   successfulJobsHistoryLimit: 3
