---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbox-data
  namespace: networking
  labels:
    kasten.io/backup-volume: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hdd-nfs-storage
