---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netbox
  namespace: networking
spec:
  releaseName: netbox
  chart:
    spec:
      # renovate: registryUrl=https://charts.boo.tc
      chart: netbox
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: bootc-charts
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  test:
    enable: false
  values:
    existingSecret: netbox-secrets
    postgresql:
      enabled: true
    redis:
      enabled: true
      auth:
        # This is temp because the chart is broken.
        # Really it can be plain text because.. redis auth is always a pain.
        # But the next chart release should fix this.
        password: "temp-12345"
      image:
        repository: library/redis
        tag: "7.0.3"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          kubernetes.io/tls-acme: "true"
          hajimari.io/appName: "Netbox"
          hajimari.io/enable: "true"
          hajimari.io/icon: "netbox"
          cert-manager.io/cluster-issuer: "letsencrypt-production" # needs cert
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: networking-traefik-forward-auth@kubernetescrd # needs oauth
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}" # needs external DNS # ? https://github.com/kubernetes-sigs/external-dns/blob/master/docs/faq.md
          external-dns/is-public: "true"
        hosts:
          - host: "netbox.${SECRET_DOMAIN}"
            http:
              paths:
                - backend:
                    serviceName: netbox
                    servicePort: 80
        tls:
          - hosts:
              - "netbox.${SECRET_DOMAIN}"
            secretName: "netbox-tls"
    persistence:
      enabled: true
      existingClaim: "netbox-data"
      accessMode: ReadWriteOnce
    reportsPersistence:
      enabled: false
