# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:t80vniPRtWWLNwlLFY1XVKhU6thJlEnPe43X6+s67+nYjV3fVQ==,iv:KtHdVDChz1ZSDk2+7vNabhmG7N+hZ9+4zwmHTC6yyMU=,tag:+lhCAuryJwE5/g5vCBBoqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l2ynvs6f5sug5hf5yzd3dedd4yusth2rwxg77xxllg8kgcdd2f8sw965ed
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbEZEZGNadFIvaGFXZ09y
            MjlIRzA5TmNORjNxaUFJcE55aFZsQWczKzJNCm1UV0hPNm9ralNOWkZhNEcrblR1
            Z0s5SERtQ2ZxdUwvY1FnZytDL3hkSjQKLS0tIDJjYXEyMmo3RGVzV3QvM1l4Ym9M
            RE54RmZlUi9kNEkvNTBjc3ZkRWVSMjgKZqpBPEihBx7jtZJ7NdvV85QcFwfEnMRb
            QZeKgeyuVgRafhTtzvq4Jbxb8l1T9EGPHiEHVzGOWuZCPBzgL8/J0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-13T18:21:47Z"
    mac: ENC[AES256_GCM,data:A+6L3kUmI/I5E9Ic3svB3/31jynNJwmFV6Me82GHqRVUzJyhEPu8upcXwmsjEbqGxOeduxsgjmka1f8GHJn/64GKXi5vOjjx9L2vnWvi04t4ZB5hjfeIxSWXXt4MqySbe9cQark5xCbQIxsmYwDI5xuhPpcezoyg5tKeOJPG8VM=,iv:/gXkqN24fOLmjdW3kzTqWinjUCyjZP07FNkB2o882gI=,tag:/ySo0hj9xSSZC3FccL5Zyg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
